/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;

/**
 *
 * @author User
 */
public class View extends javax.swing.JPanel {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewsys = new javax.swing.JTextField();
        vstock = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        viewsys.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewsys.setText("Supermarket viewing system");
        viewsys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewsysActionPerformed(evt);
            }
        });

        vstock.setText("View stock");
        vstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vstockActionPerformed(evt);
            }
        });

        jButton2.setText("View Casher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vstock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(viewsys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewsys, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vstock)
                    .addComponent(jButton2))
                .addContainerGap(203, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewsysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewsysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewsysActionPerformed

    private void vstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vstockActionPerformed
        ArrayList< Stock > list = getStockList();
        DefaultTableModel model = (DefaultTableModel)jTable.getModel();
        Obj[]row=new Obj[6];
        for (int i=0 ;i<list.size();i++)
        {
            row[0]=list.get(i).getsid();
            row[1]=list.get(i).getsname();
            row[2]=list.get(i).getprise();
            row[3]=list.get(i).getquantity();
        }
    }//GEN-LAST:event_vstockActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList< Casher > list = getCasherList();
        DefaultTableModel model =(DefaultTableModel)jTable.getModel();
        Obj[]row =new Obj[6];
        for (int i =0 ;i<list.size();i++)
        {
            row[0]=list.get(i).getid();
            row[1]=list.get(i).getname();
            row[2]=list.get(i).getmno();
            row[3]=list.get(i).getaddress();
            row[4]=list.get(i).getemail();
            row[5]=list.get(i).getpassword();
            
            model.addRow(row);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField viewsys;
    private javax.swing.JButton vstock;
    // End of variables declaration//GEN-END:variables
}
