/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;

import java.sql.Connection;
import javax.swing.JFrame;
/**
 *
 * @author OOI ZHENG YUE
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeladmin = new javax.swing.JLabel();
        jLabelcashier = new javax.swing.JLabel();
        jLabelloginform = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttonmin = new java.awt.Button();
        buttonclose = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabeladmin.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabeladmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabeladmin.setText("Admin");
        jLabeladmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeladminMouseClicked(evt);
            }
        });

        jLabelcashier.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelcashier.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcashier.setText("Cashier");
        jLabelcashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcashierMouseClicked(evt);
            }
        });

        jLabelloginform.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelloginform.setText("Login Form");

        buttonmin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonmin.setForeground(new java.awt.Color(255, 0, 0));
        buttonmin.setLabel("-");
        buttonmin.setName(""); // NOI18N
        buttonmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonminActionPerformed(evt);
            }
        });

        buttonclose.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonclose.setForeground(new java.awt.Color(255, 0, 0));
        buttonclose.setLabel("X");
        buttonclose.setName(""); // NOI18N
        buttonclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1360, 1360, 1360)
                .addComponent(buttonclose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(590, 590, 590)
                .addComponent(jLabelloginform))
            .addGroup(layout.createSequentialGroup()
                .addGap(1300, 1300, 1300)
                .addComponent(buttonmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(jLabeladmin))
            .addGroup(layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jLabelcashier))
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(buttonclose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabelloginform))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(buttonmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabeladmin))
            .addGroup(layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(jLabelcashier))
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabeladminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeladminMouseClicked
        // TODO add your handling code here:
        LoginForm rf = new LoginForm();
        rf.setVisible(true);
        rf.pack();
        rf.setLocationRelativeTo(null);
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabeladminMouseClicked

    private void jLabelcashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcashierMouseClicked
        // TODO add your handling code here:
        cashierLoginForm rf = new cashierLoginForm();
        rf.setVisible(true);
        rf.pack();
        rf.setLocationRelativeTo(null);
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelcashierMouseClicked

    private void buttonminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonminActionPerformed
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_buttonminActionPerformed

    private void buttoncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttoncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonclose;
    private java.awt.Button buttonmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabeladmin;
    private javax.swing.JLabel jLabelcashier;
    private javax.swing.JLabel jLabelloginform;
    // End of variables declaration//GEN-END:variables
}
