/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;
import java.sql.Connection;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author OOI ZHENG YUE
 */
public class RegisterForm extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    /**
     * Creates new form RegisterForm
     */
    
        public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        conn = JConnection.getConnection();
        
        Update_table();
        //show_user();
    }
    private void Update_table(){
        try{
                 String query= "select * from user";
                 conn=JConnection.getConnection();//it's a class the connection properties are defined here
                 PreparedStatement ps; 
                 ps = conn.prepareStatement(query);
                 ResultSet rs = ps.executeQuery();
                 jTableregister2.setModel(DbUtils.resultSetToTableModel(rs));


                    }

           catch(Exception ee){
               ee.printStackTrace();
           }
    }   
    /*public ArrayList<Register>Listuser(String s){
        ArrayList<Register> list = new ArrayList<>();
        
          
            Statement  st;
            ResultSet re;
        try{
            Connection conn = JConnection.ConnecrDB();
            st = conn.createStatement();
            //String sql = "SELECT * FROM 'register' where concat('ID', 'fullname', 'username', 'password', 'type') like '%"+ValToSearch+"%'";
            //pst = conn.prepareStatement(sql);
            re = pst.executeQuery();
            
            
            //DefaultTableModel model = (DefaultTableModel) jTableregister.getModel();
            //model.setRowCount(0);
            Register r;

            while(re.next()){
                r = new Register (re.getInt("ID"),re.getString("Fullname"),re.getString("Username"),re.getString("Password"),re.getString("Type"));
                list.add(r);
            }
        }catch(Exception e){

            JOptionPane.showMessageDialog(this, e);
        }
        return list;
    }
    /*public void show_user(){
        ArrayList<Register> list = Listuser(txt_search2.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"ID","Fullname","Username","Password","Type"});
        Object[] row = new Object[5];
        for(int i =0; i<list.size(); i++){
            row[0] = list.get(i).getid();
            row[1] = list.get(i).getfullname();
            row[2] = list.get(i).getusername();
            row[3] = list.get(i).getpassword(); 
            row[4] = list.get(i).gettype();
            model.addRow(row);
        }
        jTableregister2.setModel(model);
    }*/
    public ResultSet find(String s){
            Statement  st;
            ResultSet rs =null;
        try{
            Connection conn = JConnection.getConnection();
            
            pst = conn.prepareStatement("SELECT * FROM register where id=?");
            pst.setString(1, s);
           // st = conn.createStatement();
          
            rs = pst.executeQuery();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return rs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelUsername = new javax.swing.JLabel();
        txt_rfname = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        txt_rpow = new javax.swing.JPasswordField();
        jComboBoxType = new javax.swing.JComboBox<>();
        jLabelUsername1 = new javax.swing.JLabel();
        jLabelUsername2 = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        txt_runame = new javax.swing.JTextField();
        txt_search = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableregister = new javax.swing.JTable();
        view = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        txt_rtype = new javax.swing.JTextField();
        txt_rid1 = new javax.swing.JTextField();
        jButtonsearch = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelUsername3 = new javax.swing.JLabel();
        txt_rfname1 = new javax.swing.JTextField();
        jButtonSave1 = new javax.swing.JButton();
        jButtonCancel1 = new javax.swing.JButton();
        txt_rpow1 = new javax.swing.JPasswordField();
        jComboBoxType1 = new javax.swing.JComboBox<>();
        jLabelUsername4 = new javax.swing.JLabel();
        jLabelUsername5 = new javax.swing.JLabel();
        jLabelType1 = new javax.swing.JLabel();
        txt_runame1 = new javax.swing.JTextField();
        txt_search1 = new javax.swing.JTextField();
        jLabelID1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableregister1 = new javax.swing.JTable();
        view1 = new javax.swing.JButton();
        jButton_delete1 = new javax.swing.JButton();
        txt_rtype1 = new javax.swing.JTextField();
        txt_rid2 = new javax.swing.JTextField();
        jButtonsearch1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelRegisterForm = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelUsername6 = new javax.swing.JLabel();
        txt_rfname2 = new javax.swing.JTextField();
        jButtonSave2 = new javax.swing.JButton();
        txt_rpow2 = new javax.swing.JPasswordField();
        jComboBoxType2 = new javax.swing.JComboBox<>();
        jLabelUsername7 = new javax.swing.JLabel();
        jLabelUsername8 = new javax.swing.JLabel();
        jLabelType2 = new javax.swing.JLabel();
        txt_runame2 = new javax.swing.JTextField();
        txt_search2 = new javax.swing.JTextField();
        jLabelID2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableregister2 = new javax.swing.JTable();
        jButton_delete2 = new javax.swing.JButton();
        txt_rtype2 = new javax.swing.JTextField();
        txt_rid3 = new javax.swing.JTextField();
        jButtonsearch2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(226, 220, 222));

        jLabelUsername.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUsername.setText("Full Name");

        txt_rfname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_rfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rfnameActionPerformed(evt);
            }
        });

        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        txt_rpow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_rpow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rpowActionPerformed(evt);
            }
        });

        jComboBoxType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cashier", "Admin" }));
        jComboBoxType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTypeMouseClicked(evt);
            }
        });
        jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeActionPerformed(evt);
            }
        });

        jLabelUsername1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUsername1.setText("Username");

        jLabelUsername2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUsername2.setText("Password");

        jLabelType.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelType.setText("Type");

        txt_runame.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_runame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_runameActionPerformed(evt);
            }
        });

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        jLabelID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelID.setText("ID");

        jTableregister.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Fullname", "Username", "Password", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableregisterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableregister);

        view.setText("view");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        jButton_delete.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton_delete.setText("delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        txt_rtype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_rtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rtypeActionPerformed(evt);
            }
        });

        txt_rid1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_rid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rid1ActionPerformed(evt);
            }
        });

        jButtonsearch.setText("Search");
        jButtonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsearchActionPerformed(evt);
            }
        });

        jButton2.setText("Back to main manu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(226, 220, 222));

        jLabelUsername3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUsername3.setText("Full Name");

        txt_rfname1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_rfname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rfname1ActionPerformed(evt);
            }
        });

        jButtonSave1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSave1.setText("Save");
        jButtonSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSave1ActionPerformed(evt);
            }
        });

        jButtonCancel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancel1.setText("Cancel");
        jButtonCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancel1ActionPerformed(evt);
            }
        });

        txt_rpow1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_rpow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rpow1ActionPerformed(evt);
            }
        });

        jComboBoxType1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cashier", "Admin" }));
        jComboBoxType1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxType1MouseClicked(evt);
            }
        });
        jComboBoxType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxType1ActionPerformed(evt);
            }
        });

        jLabelUsername4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUsername4.setText("Username");

        jLabelUsername5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUsername5.setText("Password");

        jLabelType1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelType1.setText("Type");

        txt_runame1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_runame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_runame1ActionPerformed(evt);
            }
        });

        txt_search1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search1ActionPerformed(evt);
            }
        });

        jLabelID1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelID1.setText("ID");

        jTableregister1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Fullname", "Username", "Password", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableregister1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableregister1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableregister1);

        view1.setText("view");
        view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1ActionPerformed(evt);
            }
        });

        jButton_delete1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton_delete1.setText("delete");
        jButton_delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delete1ActionPerformed(evt);
            }
        });

        txt_rtype1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_rtype1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rtype1ActionPerformed(evt);
            }
        });

        txt_rid2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_rid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rid2ActionPerformed(evt);
            }
        });

        jButtonsearch1.setText("Search");
        jButtonsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsearch1ActionPerformed(evt);
            }
        });

        jButton3.setText("Back to main manu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelUsername5)
                        .addComponent(jLabelUsername4)
                        .addComponent(jLabelType1))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelID1)
                        .addComponent(jLabelUsername3)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonCancel1)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButton_delete1)
                                .addGap(430, 430, 430))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(view1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jComboBoxType1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_rtype1))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_rfname1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_runame1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_rpow1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(125, 125, 125)
                                        .addComponent(txt_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonsearch1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(172, 172, 172)
                    .addComponent(txt_rid2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(489, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelID1)
                                .addGap(164, 164, 164))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_rfname1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelUsername3))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_runame1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelUsername4))
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelUsername5)
                            .addComponent(txt_rpow1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelType1)
                            .addComponent(jComboBoxType1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_rtype1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonsearch1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(view1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(txt_rid2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(530, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelUsername2)
                        .addComponent(jLabelUsername1)
                        .addComponent(jLabelType))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelID)
                        .addComponent(jLabelUsername)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonCancel)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButton_delete)
                                .addGap(430, 430, 430))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_rtype))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_rfname, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_runame, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_rpow, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(125, 125, 125)
                                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonsearch)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(172, 172, 172)
                    .addComponent(txt_rid1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(489, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelID)
                                .addGap(164, 164, 164))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_rfname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelUsername))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_runame, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelUsername1))
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelUsername2)
                            .addComponent(txt_rpow, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelType)
                            .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_rtype, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonsearch))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(txt_rid1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(530, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 228, 232));

        jLabelRegisterForm.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelRegisterForm.setForeground(new java.awt.Color(255, 51, 255));
        jLabelRegisterForm.setText("Register Form");

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 0, 0));
        jLabelClose.setText("x");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabelRegisterForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 595, Short.MAX_VALUE)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMin)
                    .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(613, 613, 613))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelRegisterForm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(226, 220, 222));

        jLabelUsername6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUsername6.setText("Full Name");

        txt_rfname2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_rfname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rfname2ActionPerformed(evt);
            }
        });

        jButtonSave2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSave2.setText("Save");
        jButtonSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSave2ActionPerformed(evt);
            }
        });

        txt_rpow2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_rpow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rpow2ActionPerformed(evt);
            }
        });

        jComboBoxType2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cashier", "Admin" }));
        jComboBoxType2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxType2MouseClicked(evt);
            }
        });
        jComboBoxType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxType2ActionPerformed(evt);
            }
        });

        jLabelUsername7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUsername7.setText("Username");

        jLabelUsername8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUsername8.setText("Password");

        jLabelType2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelType2.setText("Type");

        txt_runame2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_runame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_runame2ActionPerformed(evt);
            }
        });

        txt_search2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search2ActionPerformed(evt);
            }
        });
        txt_search2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search2KeyReleased(evt);
            }
        });

        jLabelID2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelID2.setText("ID");

        jTableregister2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Fullname", "Username", "Password", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableregister2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jTableregister2AncestorRemoved(evt);
            }
        });
        jTableregister2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableregister2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableregister2);

        jButton_delete2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton_delete2.setText("delete");
        jButton_delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delete2ActionPerformed(evt);
            }
        });

        txt_rtype2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_rtype2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rtype2ActionPerformed(evt);
            }
        });

        txt_rid3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_rid3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rid3ActionPerformed(evt);
            }
        });

        jButtonsearch2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonsearch2.setText("Search");
        jButtonsearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsearch2ActionPerformed(evt);
            }
        });

        jButton4.setText("Back to main manu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelUsername8)
                        .addComponent(jLabelUsername7)
                        .addComponent(jLabelType2))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelID2)
                        .addComponent(jLabelUsername6)))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jButtonSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jButton_delete2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(txt_rid3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jComboBoxType2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_rtype2))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_rfname2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_runame2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_rpow2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(txt_search2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonsearch2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_rid3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelID2))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_rfname2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelUsername6)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton4)
                                .addGap(40, 40, 40)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonsearch2)
                                    .addComponent(txt_search2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_runame2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUsername7))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelUsername8)
                            .addComponent(txt_rpow2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelType2)
                            .addComponent(jComboBoxType2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_rtype2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_delete2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void txt_rfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rfnameActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:

        try{
            String sql = "Insert into register(ID,fullname,username,password,type) values(?,?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1,txt_rid3.getText() );
            pst.setString(2,txt_rfname2.getText() );
            pst.setString(3,txt_runame2.getText() );
            pst.setString(4,txt_rpow2.getText() );
            pst.setObject(5,jComboBoxType2.getSelectedItem());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Saved");
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        Update_table();

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
         LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void txt_rpowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rpowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rpowActionPerformed

    private void jComboBoxTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTypeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeMouseClicked

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxTypeActionPerformed

    private void txt_runameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_runameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_runameActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
        //show_user();
    }//GEN-LAST:event_txt_searchActionPerformed

    private void jTableregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableregisterMouseClicked
        // TODO add your handling code here:
         int i = jTableregister2.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) jTableregister2.getModel();
            txt_rid3.setText(model.getValueAt(i,0).toString());
            txt_rfname2.setText(model.getValueAt(i,1).toString());
            txt_runame2.setText(model.getValueAt(i,2).toString());
            txt_rpow2.setText(model.getValueAt(i,3).toString());
            txt_rtype2.setText(model.getValueAt(i,4).toString());
            //jComboBoxType.setText(model.getValueAt(i,4));
            Update_table();

    }//GEN-LAST:event_jTableregisterMouseClicked

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:

        try{
            Connection conn = JConnection.getConnection();
            PreparedStatement  pst = conn.prepareStatement("select * from Register");
            ResultSet re = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTableregister2.getModel();
            model.setRowCount(0);

            while(re.next()){
                Object o[] = { re.getInt("ID"),re.getString("Fullname"),re.getString("Username"),re.getString("Password"),re.getString("Type")};
                model.addRow(o);
            }
        }catch(Exception e){

            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_viewActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
         DefaultTableModel model = (DefaultTableModel) jTableregister2.getModel();
        // get selected row index
        int SelectedRowIndex = jTableregister2.getSelectedRow();
        model.removeRow(SelectedRowIndex);
        
        
        String sql = "delete from Register where id =?";
        
        try{
            PreparedStatement  pst = conn.prepareStatement(sql);
            pst.setString(1,txt_rid3.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "delete");
            
        }catch(Exception e){
           
            JOptionPane.showMessageDialog(null, e);
        }
        Update_table();
        txt_rid3.setText("");
        txt_rfname2.setText("");
        txt_runame2.setText("");
        txt_rpow2.setText("");
        txt_rtype2.setText("");
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void txt_rtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rtypeActionPerformed

    private void txt_rid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rid1ActionPerformed

    private void jButtonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsearchActionPerformed
        // TODO add your handling code he
        RegisterForm r = new RegisterForm();
        ResultSet rs = null;
        
        rs = r.find(txt_rid3.getText());
        try{
            if(rs.next()){
                txt_rfname2.setText(rs.getString("fullname"));
                txt_runame2.setText(rs.getString("username"));
                txt_rpow2.setText(rs.getString("password"));
                txt_rtype2.setText(rs.getString("type"));
                
            }else{
                JOptionPane.showMessageDialog(null, "No Data For This Id");
            }
        }catch(Exception e){
           
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButtonsearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        homeadmin form = new homeadmin();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_rfname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rfname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rfname1ActionPerformed

    private void jButtonSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSave1ActionPerformed

    private void jButtonCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancel1ActionPerformed

    private void txt_rpow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rpow1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rpow1ActionPerformed

    private void jComboBoxType1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxType1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxType1MouseClicked

    private void jComboBoxType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxType1ActionPerformed

    private void txt_runame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_runame1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_runame1ActionPerformed

    private void txt_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search1ActionPerformed

    private void jTableregister1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableregister1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableregister1MouseClicked

    private void view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view1ActionPerformed

    private void jButton_delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_delete1ActionPerformed

    private void txt_rtype1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rtype1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rtype1ActionPerformed

    private void txt_rid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rid2ActionPerformed

    private void jButtonsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonsearch1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_rfname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rfname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rfname2ActionPerformed

    private void jButtonSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSave2ActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "Insert into user(ID,fullname,username,password,type) values(?,?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1,txt_rid3.getText() );
            pst.setString(2,txt_rfname2.getText() );
            pst.setString(3,txt_runame2.getText() );
            pst.setString(4,txt_rpow2.getText() );
            pst.setObject(5,jComboBoxType2.getSelectedItem());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Saved");
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        Update_table();
    }//GEN-LAST:event_jButtonSave2ActionPerformed

    private void txt_rpow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rpow2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rpow2ActionPerformed

    private void jComboBoxType2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxType2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxType2MouseClicked

    private void jComboBoxType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxType2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxType2ActionPerformed

    private void txt_runame2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_runame2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_runame2ActionPerformed

    private void txt_search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search2ActionPerformed

    private void jTableregister2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableregister2MouseClicked
        // TODO add your handling code here:
         int i = jTableregister2.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) jTableregister2.getModel();
            txt_rid3.setText(model.getValueAt(i,0).toString());
            txt_rfname2.setText(model.getValueAt(i,1).toString());
            txt_runame2.setText(model.getValueAt(i,2).toString());
            txt_rpow2.setText(model.getValueAt(i,3).toString());
            txt_rtype2.setText(model.getValueAt(i,4).toString());
            //jComboBoxType.setText(model.getValueAt(i,4));
            Update_table();
    }//GEN-LAST:event_jTableregister2MouseClicked

    private void jButton_delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delete2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableregister2.getModel();
        // get selected row index
        int SelectedRowIndex = jTableregister2.getSelectedRow();
        model.removeRow(SelectedRowIndex);
        
        
        String sql = "delete from user where id =?";
        
        try{
            PreparedStatement  pst = conn.prepareStatement(sql);
            pst.setString(1,txt_rid3.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "delete");
            
        }catch(Exception e){
           
            JOptionPane.showMessageDialog(null, e);
        }
        Update_table();
        txt_rid3.setText("");
        txt_rfname2.setText("");
        txt_runame2.setText("");
        txt_rpow2.setText("");
        txt_rtype2.setText("");
    }//GEN-LAST:event_jButton_delete2ActionPerformed

    private void txt_rtype2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rtype2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rtype2ActionPerformed

    private void txt_rid3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rid3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rid3ActionPerformed

    private void jButtonsearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsearch2ActionPerformed
        // TODO add your handling code here:
      //  show_user();
        RegisterForm r = new RegisterForm();
        ResultSet rs = null;
        
        rs = r.find(txt_search2.getText());
        try{
            if(rs.next()){
                txt_rid3.setText(rs.getString("id"));
                txt_rfname2.setText(rs.getString("fullname"));
                txt_runame2.setText(rs.getString("username"));
                txt_rpow2.setText(rs.getString("password"));
                txt_rtype2.setText(rs.getString("type"));
                
            }else{
                JOptionPane.showMessageDialog(null, "No Data For This Id");
            }
        }catch(Exception e){
           
            JOptionPane.showMessageDialog(null, e);
        }
        txt_search2.setText("");
    }//GEN-LAST:event_jButtonsearch2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        homeadmin lgf = new homeadmin();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTableregister2AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTableregister2AncestorRemoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTableregister2AncestorRemoved

    private void txt_search2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCancel1;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSave1;
    private javax.swing.JButton jButtonSave2;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_delete1;
    private javax.swing.JButton jButton_delete2;
    private javax.swing.JButton jButtonsearch;
    private javax.swing.JButton jButtonsearch1;
    private javax.swing.JButton jButtonsearch2;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JComboBox<String> jComboBoxType1;
    private javax.swing.JComboBox<String> jComboBoxType2;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelID1;
    private javax.swing.JLabel jLabelID2;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelRegisterForm;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelType1;
    private javax.swing.JLabel jLabelType2;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelUsername1;
    private javax.swing.JLabel jLabelUsername2;
    private javax.swing.JLabel jLabelUsername3;
    private javax.swing.JLabel jLabelUsername4;
    private javax.swing.JLabel jLabelUsername5;
    private javax.swing.JLabel jLabelUsername6;
    private javax.swing.JLabel jLabelUsername7;
    private javax.swing.JLabel jLabelUsername8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableregister;
    private javax.swing.JTable jTableregister1;
    private javax.swing.JTable jTableregister2;
    private javax.swing.JTextField txt_rfname;
    private javax.swing.JTextField txt_rfname1;
    private javax.swing.JTextField txt_rfname2;
    private javax.swing.JTextField txt_rid1;
    private javax.swing.JTextField txt_rid2;
    private javax.swing.JTextField txt_rid3;
    private javax.swing.JPasswordField txt_rpow;
    private javax.swing.JPasswordField txt_rpow1;
    private javax.swing.JPasswordField txt_rpow2;
    private javax.swing.JTextField txt_rtype;
    private javax.swing.JTextField txt_rtype1;
    private javax.swing.JTextField txt_rtype2;
    private javax.swing.JTextField txt_runame;
    private javax.swing.JTextField txt_runame1;
    private javax.swing.JTextField txt_runame2;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_search1;
    private javax.swing.JTextField txt_search2;
    private javax.swing.JButton view;
    private javax.swing.JButton view1;
    // End of variables declaration//GEN-END:variables
}
